### ISSUE TITLE
Cannot read properties of undefined (reading 'sqlTable')

### ISSUE THREAD

**Issue by mortifia** [acarl005/join-monster#464]
hello !
would anyone know why the setting is not detected? or how to solve it?

graphql query : 
```graphql
query {
  books{
    id 
    title
  }
}
```

graphql response:

```json
{
  "errors": [
    {
      "message": "Cannot read properties of undefined (reading 'sqlTable')",
      "locations": [
        {
          "line": 1,
          "column": 8
        }
      ],
      "path": [
        "books"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read properties of undefined (reading 'sqlTable')",
            "    at Object.populateASTNode (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/query-ast-to-sql-ast/index.js:143:88)",
            "    at Object.queryASTToSqlAST (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/query-ast-to-sql-ast/index.js:78:19)",
            "    at Object.<anonymous> (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/index.js:9:29)",
            "    at Generator.next (<anonymous>)",
            "    at step (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/index.js:103:191)",
            "    at /home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/index.js:103:437",
            "    at new Promise (<anonymous>)",
            "    at Object.<anonymous> (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/index.js:103:99)",
            "    at Object.joinMonster [as default] (/home/mortifia/Bureau/heuuu/node_modules/join-monster/dist/index.js:37:17)",
            "    at resolve (file:///home/mortifia/Bureau/heuuu/build/index.js:34:43)"
          ]
        }
      }
    }
  ],
  "data": {
    "books": null
  }
}
```

code ts
```ts
import { ApolloServer } from 'apollo-server-express';
//import { GraphQLResolverMap } from 'apollo-graphql';
import { ApolloServerPluginDrainHttpServer } from 'apollo-server-core';
import express from 'express';
import http from 'http';
import joinMonster from 'join-monster';
import { GraphQLInt, GraphQLList, GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import postgres from 'postgres';

const db = postgres('postgres://heuuu:heuuu@localhost:5432/heuuu')
db`SELECT * FROM books.books`.then((heuu) => { console.log(heuu) });
/* test return
[
  { id: -1, title: 'heuuu holala' },
  count: 1,
  columns: [
    { name: 'id', parser: [Function: parse], type: 23 },
    { name: 'title', parser: undefined, type: 1043 }
  ],
  command: 'SELECT',
  state: { status: 'I', pid: 15763, secret: -717060963 }
]
*/

//!    ok ???
const Book = new GraphQLObjectType({
  name: 'Book',
  extensions: {
    joinMonster: {
      sqlTable: 'books.books',
      uniqueKey: 'id',
    }
  },
  fields: () => ({
    id: {
      type: GraphQLInt
    },
    title: {
      type: GraphQLString
    }
  })
})

//!    ok ???
const QueryRoot = new GraphQLObjectType({
  name: 'Query',
  fields: () => ({
    books: {
      type: new GraphQLList(Book),
      resolve: (parent, args, context, resolveInfo) => {
        return joinMonster.default(resolveInfo, {}, (sql: string) => { // yes forced to use default to work
          return db(sql);
        })
      },
    }
  })
})

//!    ok ???
var schema = new GraphQLSchema({
  query: QueryRoot,
  description: 'huhuhu'
})

// all ok here
async function startApolloServer(schema: GraphQLSchema) {
  const app = express();
  const httpServer = http.createServer(app);
  const server = new ApolloServer({
    schema: schema,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer }),],
  });
  await server.start();
  server.applyMiddleware({ app });
  await new Promise<void>(resolve => httpServer.listen({ port: 4000 }, resolve));
  //await httpServer.listen({ port: 4000 });
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`);
}

startApolloServer(schema)
```

package.json
```json
{
  "name": "heuuu",
  "version": "1.0.0",
  "description": "",
  "main": "build/index.js",
  "type": "module",
  "scripts": {
    "start": "node ./build/index.js",
    "build": "tsc",
    "build-start": "tsc && node ./build/index.js",
    "dev": "concurrently \"tsc -w\" \"nodemon --inspect build/index\"",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "xxxx",
  "dependencies": {
    "apollo-server": "^3.4.0",
    "apollo-server-express": "^3.4.0",
    "express": "^4.17.1",
    "graphql": "^16.0.1",
    "join-monster": "^2.1.2",
    "postgres": "^2.0.0-beta.10"
  },
  "devDependencies": {
    "@types/node": "^16.11.2",
    "concurrently": "^6.3.0",
    "nodemon": "^2.0.13",
    "typescript": "^4.4.4"
  }
}
```

work on :
  ubuntu 20
  node v16.13.0

**Comment by mortifia** [comment]
Schema 
![image](https://user-images.githubusercontent.com/22671054/140608328-807f2f4e-3783-4ca5-ab57-a520397b22aa.png)

**Comment by nicoabie** [comment]
Check https://github.com/join-monster/join-monster-sscce for a working example
